In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("/Users/habibabassem/Downloads/train.csv")

In [3]:
dataset

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
5          0       0       0       0       0       0       0       0       0   
6          7       0       0       0       0       0       0       0       0   
7          3       0       0       0       0       0       0       0       0   
8          5       0       0       0       0       0       0       0       0   
9          3       0       0       0       0       0       0       0       0   
10         8       0       0       0       0       0       0       0       0   
11         9       0       0       0       0       0       0       0       0   
12         1       0       0       0       0       0       0       0       0   
13         3       0       0       0       0       0       0       0       0   
14         3       0       0       0       0       0       0       0       0   
15         1       0       0       0       0       0       0       0       0   
16         2       0       0       0       0       0       0       0       0   
17         0       0       0       0       0       0       0       0       0   
18         7       0       0       0       0       0       0       0       0   
19         5       0       0       0       0       0       0       0       0   
20         8       0       0       0       0       0       0       0       0   
21         6       0       0       0       0       0       0       0       0   
22         2       0       0       0       0       0       0       0       0   
23         0       0       0       0       0       0       0       0       0   
24         2       0       0       0       0       0       0       0       0   
25         3       0       0       0       0       0       0       0       0   
26         6       0       0       0       0       0       0       0       0   
27         9       0       0       0       0       0       0       0       0   
28         9       0       0       0       0       0       0       0       0   
29         7       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970      2       0       0       0       0       0       0       0       0   
41971      3       0       0       0       0       0       0       0       0   
41972      4       0       0       0       0       0       0       0       0   
41973      4       0       0       0       0       0       0       0       0   
41974      3       0       0       0       0       0       0       0       0   
41975      9       0       0       0       0       0       0       0       0   
41976      2       0       0       0       0       0       0       0       0   
41977      4       0       0       0       0       0       0       0       0   
41978      4       0       0       0       0       0       0       0       0   
41979      4       0       0       0       0       0       0       0       0   
41980      7       0       0       0       0       0       0       0       0   
41981      2       0       0       0       0       0       0       0       0   
41982      8       0       0       0       0       0       0       0       0   
41983      7       0       0       0       0       0       0       0       0   
41984      3       0       0       0       0       0       0       0       0   
41985      3       0       0       0       0       0       0       0       0   
41986      0       0       0       0       0       0       0       0       0   
41987      5       0       0       0       0       0       0       0       0   
41988  

In [4]:
xtrain = dataset.loc[:,"pixel0":"pixel783"]
print (xtrain)

       pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       

In [5]:
ytrain = dataset["label"]
print (ytrain)

0        1
1        0
2        1
3        4
4        0
5        0
6        7
7        3
8        5
9        3
10       8
11       9
12       1
13       3
14       3
15       1
16       2
17       0
18       7
19       5
20       8
21       6
22       2
23       0
24       2
25       3
26       6
27       9
28       9
29       7
        ..
41970    2
41971    3
41972    4
41973    4
41974    3
41975    9
41976    2
41977    4
41978    4
41979    4
41980    7
41981    2
41982    8
41983    7
41984    3
41985    3
41986    0
41987    5
41988    0
41989    5
41990    3
41991    1
41992    9
41993    6
41994    4
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64


In [6]:
dataset2 = pd.read_csv("/Users/habibabassem/Downloads/test (1).csv")
xtest = dataset2.loc[:,"pixel0":"pixel783"]
print (xtest)

       pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       

In [7]:
testLabel = pd.read_csv("/Users/habibabassem/Downloads/sample_submission.csv")
# print (testLabel)
ytest = testLabel['Label']
print (ytest)

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
27970    0
27971    0
27972    0
27973    0
27974    0
27975    0
27976    0
27977    0
27978    0
27979    0
27980    0
27981    0
27982    0
27983    0
27984    0
27985    0
27986    0
27987    0
27988    0
27989    0
27990    0
27991    0
27992    0
27993    0
27994    0
27995    0
27996    0
27997    0
27998    0
27999    0
Name: Label, Length: 28000, dtype: int64


In [8]:
import sklearn as sk
from sklearn import svm

In [10]:
clf = svm.SVC(gamma='scale')

In [11]:
clf.fit(xtrain, ytrain)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [12]:
ypredict = clf.predict(xtest)

In [12]:
from sklearn.metrics import confusion_matrix

In [14]:
cm = confusion_matrix(ytest, ypredict)

In [15]:
cm

array([[2775, 3212, 2850, 2764, 2773, 2512, 2750, 2884, 2727, 2753],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [96]:
def accuracy_metrics(y_true, y_predict): 
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(y_true, y_predict)
    error_rate = 1 - accuracy
    from sklearn.metrics import precision_score
    precision = precision_score(y_true, y_predict, average='micro')  
    from sklearn.metrics import recall_score
    recall = recall_score(y_true, y_predict, average='micro')  
    return (accuracy, error_rate, precision, recall)

In [22]:
SVMacc, SVMerr, SVMpre, SVMrec = accuracy_metrics(ytest, ypredict)
print (SVMacc)
print (SVMerr)
print (SVMpre)
print (SVMrec)

0.09910714285714285
0.9008928571428572
0.09910714285714285
0.09910714285714285


In [16]:
SVMnonLin = svm.SVC(gamma='scale', kernel = "rbf", max_iter = 1000)

In [17]:
SVMnonLin.fit(xtrain, ytrain) 

/Users/habibabassem/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/svm/base.py:241: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=1000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
ypredictNonLin = SVMnonLin.predict(xtest)

In [20]:
cmNonLin = confusion_matrix(ytest, ypredictNonLin)

In [21]:
print (cmNonLin)

[[2775 3212 2850 2764 2773 2511 2750 2883 2726 2756]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]]


In [22]:
SVMnonacc, SVMnonerr, SVMnonpre, SVMnonrec = accuracy_metrics(ytest, ypredictNonLin)
print (SVMnonacc)
print (SVMnonerr)
print (SVMnonpre)
print (SVMnonrec)

0.09910714285714285
0.9008928571428572
0.09910714285714285
0.09910714285714285


In [23]:
from sklearn.neural_network import MLPClassifier
MLPC = MLPClassifier()

In [24]:
MLPC_train = MLPC.fit(xtrain,ytrain)

In [26]:
y_MLPC = MLPC_train.predict(xtest)

In [34]:
cmMLP = confusion_matrix(ytest, y_MLPC)

In [35]:
print(cmMLP)

[[2827 3196 2769 2779 2728 2497 2826 2863 2737 2778]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]]


In [38]:
MLPacc, MLPerr, MLPpre, MLPrec = accuracy_metrics(ytest, y_MLPC)
print (MLPacc)
print (MLPerr)
print (MLPpre)
print (MLPrec)

0.10096428571428571
0.8990357142857143
0.10096428571428571
0.10096428571428571


In [29]:
MLPC2 = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(20, 10, 7, 2), random_state=1)

In [30]:
MLPC_train2 = MLPC2.fit(xtrain,ytrain)

In [31]:
y_MLPC2 = MLPC_train2.predict(xtest)

In [36]:
cmMLP2 = confusion_matrix(ytest, y_MLPC2)

In [37]:
print(cmMLP2)

[[10691    24  2626    12     9  2403  2494  7709  1575   457]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]]


In [39]:
MLPacc2, MLPerr2, MLPpre2, MLPrec2 = accuracy_metrics(ytest, y_MLPC2)
print (MLPacc2)
print (MLPerr2)
print (MLPpre2)
print (MLPrec2)

0.3818214285714286
0.6181785714285715
0.3818214285714286
0.3818214285714286


In [47]:
from sklearn import preprocessing

In [48]:
min_max_scaler = preprocessing.MinMaxScaler()

In [51]:
xtrain_scaled = min_max_scaler.fit_transform(xtrain)
xtest_scaled = min_max_scaler.fit_transform(xtest)

In [57]:
MLPC_train_scaled = MLPC2.fit(xtrain_scaled,ytrain)

In [58]:
y_MLPC_scaled = MLPC_train_scaled.predict(xtest)

In [59]:
cmMLP_scaled = confusion_matrix(ytest, y_MLPC_scaled)

In [60]:
print(cmMLP_scaled)

[[   41  3283    24    22   536 23912    68     9   105]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]]


In [62]:
MLPaccScaled, MLPerrScaled, MLPpreScaled, MLPrecScaled = accuracy_metrics(ytest, y_MLPC_scaled)
print (MLPaccScaled)
print (MLPerrScaled)
print (MLPpreScaled)
print (MLPrecScaled)

0.0014642857142857142
0.9985357142857143
0.0014642857142857142
0.0014642857142857142


In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
scaler = StandardScaler()

In [66]:
scaler.fit(xtrain)
scaler.fit(xtest)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [67]:
xtrainZ = scaler.transform(xtrain)

In [68]:
xtestZ = scaler.transform(xtest)

In [69]:
MLPC_trainZ = MLPC2.fit(xtrain,ytrain)

In [70]:
y_MLPCZ = MLPC_trainZ.predict(xtest)

In [71]:
cmMLPZ = confusion_matrix(ytest, y_MLPCZ)

In [72]:
print(cmMLPZ)

[[10691    24  2626    12     9  2403  2494  7709  1575   457]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]]


In [73]:
MLPaccZ, MLPerrZ, MLPpreZ, MLPrecZ = accuracy_metrics(ytest, y_MLPCZ)
print (MLPaccZ)
print (MLPerrZ)
print (MLPpreZ)
print (MLPrecZ)

0.3818214285714286
0.6181785714285715
0.3818214285714286
0.3818214285714286


In [40]:
MLPC3 = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(20, 10, 7, 5, 2), random_state=1)

In [42]:
MLPC_train3 = MLPC3.fit(xtrain,ytrain)

In [43]:
y_MLPC3 = MLPC_train3.predict(xtest)

In [44]:
cmMLP3 = confusion_matrix(ytest, y_MLPC3)

In [45]:
print(cmMLP3)

[[ 3131 10037    56  1219  3161   488  4530  2783  2595]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0]]


In [46]:
MLPacc3, MLPerr3, MLPpre3, MLPrec3 = accuracy_metrics(ytest, y_MLPC3)
print (MLPacc3)
print (MLPerr3)
print (MLPpre3)
print (MLPrec3)

0.11182142857142857
0.8881785714285715
0.11182142857142857
0.11182142857142857


In [10]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [11]:
import matplotlib.pyplot as plt
plt.imshow(X_train[0])

In [12]:
#reshape data to fit model
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)

In [13]:
from keras.utils import to_categorical
#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

In [8]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
#train the model
model.fit(X_train, y_train, epochs=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10


In [148]:
CNNpredict = model.predict(X_test)

In [149]:
CNNpredict = CNNpredict.astype(int)
CNNpredict

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [151]:
y_test = y_test.astype(int)
y_test

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [152]:
CNNacc, CNNerr, CNNpre, CNNrec = accuracy_metrics(y_test, CNNpredict)
print (CNNacc)
print (CNNerr)
print (CNNpre)
print (CNNrec)

0.7615
0.23850000000000005
0.6475311147468159
0.7615


In [ ]:
#train the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3


In [5]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
from keras.regularizers import l2
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(28,28,1), kernel_regularizer=l2(0.01), bias_regularizer=l2(0.01)))
model.add(Conv2D(32, kernel_size=3, activation='relu', kernel_regularizer=l2(0.01), bias_regularizer=l2(0.01)))
model.add(Flatten())
model.add(Dense(10, activation='softmax', kernel_regularizer=l2(0.01), bias_regularizer=l2(0.01)))

In [6]:
#compile model using accuracy to measure model performance
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
#train the model
model.fit(X_train, y_train, epochs=3)